### ISSUE TITLE
有测试过启用压缩码，启用压缩之后，浏览器端就读取不到数据了

### ISSUE THREAD

**Issue by darvenking** [go-netty/go-netty-ws#3]
版本：v1.0.2
启用压缩的参数：

```
	zip := nettyws.WithCompress(7, 1)
	var ws = nettyws.NewWebsocket(zip)
```

错误信息：
![image](https://github.com/go-netty/go-netty-ws/assets/10860818/fa34f17d-e309-4f38-8cc8-45bd40d24a8d)

**Comment by limpo1989** [comment]
我们这边的业务前端有nginx负责接入(wss/压缩)和负载均衡，后端的业务没有启用压缩，websocket协议压缩我测试过 server/client端，但是没有仔细测试过与浏览器压缩交互这块，具体原因我查一查

**Comment by limpo1989** [comment]
@lifespy 可以更新到 v1.0.3版本，修复了压缩相关问题

**Comment by darvenking** [comment]
> @lifespy 可以更新到 v1.0.3版本，修复了压缩相关问题

确实OK了 点赞
