### ISSUE TITLE
大佬，我又来了，作为client时，可以加一个自定义header的方法吗

### ISSUE THREAD

**Issue by darvenking** [go-netty/go-netty-ws#5]
大佬，我又来了，作为client时，可以加一个自定义header的方法吗

**Comment by limpo1989** [comment]
目前的接口没有暴露出来，我添加一下支持

**Comment by darvenking** [comment]
> 目前的接口没有暴露出来，我添加一下支持

非常感谢，可以把一些常用的都暴露下，比如代理，请求头啥的，这些还是比较常用的

**Comment by limpo1989** [comment]
请求头加上了 https://github.com/go-netty/go-netty-ws/releases/tag/v1.0.4  可以参考例子里面的姿势

> 比如代理   

代理后面我空了来加上

**Comment by darvenking** [comment]
`非常感谢！`

**Comment by limpo1989** [comment]
@lifespy 代理也加上了 [v1.0.5](https://github.com/go-netty/go-netty-ws/releases/tag/v1.0.5)

**Comment by darvenking** [comment]
> @lifespy 代理也加上了 [v1.0.5](https://github.com/go-netty/go-netty-ws/releases/tag/v1.0.5)

大佬给力！辛苦了
